### ISSUE TITLE
Create / Read features for Garden

### ISSUE THREAD

**Issue by daiHash** [ice-cream-the-fat-cat/ice-cream-backend#6]

**Comment by yukari-n-erb** [comment]
Memo : API schema

https://dbdiagram.io/d/6120bfd96dc2bb6073b4fd40

**Comment by daiHash** [comment]
@yukari-n-erb 
Please check the comments in this PR when implementing the endpoints
https://github.com/ice-cream-the-fat-cat/ice-cream-backend/pull/11
